server:
  port: 11001
  application:
    name: spring-mvc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.1.8:8066/sales_order?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: sims-order-dxhy
    password: 1hOxERyrVeGD
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 600000
      pool-name: OrderHikariCP
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1
# interceptor.enableBasicParamsInterceptor
mybatis:
  mapper-locations: classpath:com/fankf/springmvc/mapper/*.xml
  type-aliases-package: com.fankf.springmvc.dao
  config-location: classpath:mybatis-config.xml

