server:
  port: 9006
spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
#          {application}/{profile}[/{label}]  [/{label}]/{application}-{profile}{.yml|.properties|.json}

#            　　规则简单说明：{application}=配置消费方应用名称（即：config client的项目名，通俗讲：就是谁用这个配置就是谁的名字）,{profile}=配置环境（如：dev开发环境,test测试环境,prod生产环境）,{label}=仓库分支名（git或svn方式指定，native本地方式无需指定），.yml|.properties|.json表示指定的响应返回格式，{}表示必需,[]表示可选，|表示或的关系，例如本Demo项目访问：
#            　　http://localhost:8866/configclient/dev 、http://localhost:8866/configclient/dev/master
#            　　http://localhost:8866/configclient-dev.yml、http://localhost:8866/configclient-dev.properties、
#               http://localhost:8866/configclient-dev.json、http://localhost:8866/master/configclient-dev.yml
          uri: https://github.com/fankf/daily-works
          search-paths: config
          username:
          password:
          default-label: master
