server:
  port: 11000
  application:
    name: spring-mvc
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 600000
      pool-name: OrderHikariCP
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1

  main:
    allow-bean-definition-overriding: true
#  servlet:
#    context-path: /mvc
# interceptor.enableBasicParamsInterceptor
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fankf.springmvc.dao
  config-location: classpath:mybatis-config.xml

# 自定义

okHttp:
  retryCount: 3
  urls: http://localhost:8080,http://localhost:11000/get/name,http://localhost:11000/put0
