spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
    endpoint:
      bus-refresh:
        enabled: true