server:
  port: 11000
  application:
    name: spring-mvc
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 600000
      pool-name: OrderHikariCP
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1

  main:
    allow-bean-definition-overriding: true
#  servlet:
#    context-path: /mvc
# interceptor.enableBasicParamsInterceptor
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fankf.springmvc.dao
  config-location: classpath:mybatis-config.xml

# 自定义

okHttp:
  retryCount: 1
  urls: http://localhost:11000/get/aaaa,http://localhost:11000/get/a,http://localhost:8080/r

# Kafka topic 创建参数 partition 分区  replication-ractor 备份
kafka:
  #=============== provider  =======================
  bootstrap-servers: 10.1.1.8:9092
  session-out: 30000
  retry: 3
  # 每次批量发送消息的数量
  batch-size: 232840
  buffer-memory: 33554432
#  username: tx_ckafka_test
#  password: o4dsPLezJUkmcYn1
  username:
  password:
  ##=============== consumer  =======================
  consumer-groupId: user-group-0
  auto-commit-interval: 5000
  enable.auto.commit: false
  max-poll_num: 10


z-username: 123
z-password: 123